/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.joanna.bednarczyk.advent.of.code;

import pl.joanna.bednarczyk.advent.of.code.day_01.CalorieCounting;
import pl.joanna.bednarczyk.advent.of.code.day_02.RockPaperScissors;
import pl.joanna.bednarczyk.advent.of.code.day_03.RucksackReorganization;

public class App {
    public static void main(String[] args) {
        System.out.println("Advent of Code 2022!");

        System.out.println("Day One:");

//        CalorieCounting seeker = new CalorieCounting();
//        System.out.println("Part 1: " + seeker.getTheMostCalories());
//        System.out.println("Part 2: " + seeker.getTotalOfTopThree());
//
//        System.out.println("Day Two:");
//
//        RockPaperScissors tournament = new RockPaperScissors();
//        System.out.println("Part 1: " + tournament.getScore());
//        System.out.println("Part 2: " + tournament.getScorePredictedByElf());

        System.out.println("Day Three:");

        RucksackReorganization reorganization = new RucksackReorganization();
        System.out.println("Part 1: " + reorganization.getSumOfPriorities());
        System.out.println("Part 2: " );


    }
}
