/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.joanna.bednarczyk.advent.of.code;

import pl.joanna.bednarczyk.advent.of.code.day_05.SupplyStacks;
import pl.joanna.bednarczyk.advent.of.code.day_06.TuningTrouble;

public class App {
    public static void main(String[] args) {
        System.out.println("Advent of Code 2022!");

//        System.out.println("Day One:");

//        CalorieCounting seeker = new CalorieCounting();
//        System.out.println("Part 1: " + seeker.getTheMostCalories());
//        System.out.println("Part 2: " + seeker.getTotalOfTopThree());
//
//        System.out.println("Day Two:");
//
//        RockPaperScissors tournament = new RockPaperScissors();
//        System.out.println("Part 1: " + tournament.getScore());
//        System.out.println("Part 2: " + tournament.getScorePredictedByElf());

//        System.out.println("Day Three:");
//
//        RucksackReorganization reorganization = new RucksackReorganization();
//        System.out.println("Part 1: " + reorganization.getSumOfPriorities());
//        System.out.println("Part 2: " + reorganization.getSumOfBadgesPriorities());

//        System.out.println("Day Four:");
//
//        CampCleanup cleanup = new CampCleanup();
//        System.out.println("Part 1: " + cleanup.getNumberOfFullyContained());
//        System.out.println("Part 2: " + cleanup.getNumberOfOverlaps());
//
//        System.out.println("Day Five:");
//
//        SupplyStacks supplyStacks = new SupplyStacks();
//        System.out.println("Part 1: " + supplyStacks.getTopOfStacksMover9000());
//        System.out.println("Part 2: " + supplyStacks.getTopOfStacksMover9001());

        System.out.println("Day Six:");

        TuningTrouble tuningTrouble = new TuningTrouble();
        System.out.println("Part 1: " + tuningTrouble.getMarkersEnd());
        System.out.println("Part 2: ");



    }
}
